version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:4.0-management
    hostname: {{ inventory_hostname }}
    container_name: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=294DZM3HDoLMid6  # Set your Erlang cookie here
    volumes:
      - ./data:/var/lib/rabbitmq
    network_mode: "host"
