---
- name: Create RabbitMQ cluster
  hosts: servers  # group name in your inventory file
  become: true    # for root access if required
  tasks:
    - name: Add all servers' IPs and hostnames to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
        state: present
      with_items: "{{ groups['servers'] }}"

    - name: Ensure dependencies (ca-certificates, curl) are installed
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: Add Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to apt sources list
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
    - name: Copy the Docker Compose template and customize it for the host
      template:
        src: ./docker-compose.yml.j2
        dest: /home/ubuntu/docker-compose.yml
        mode: '0600'


    - name: Ensure RabbitMQ container is running
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/
        state: present
